previews:
    generation: automatic

services:
    - type: web
      name: social-fitness-app-backend
      runtime: php
      plan: free

      envVars:
          # 環境名は previewValue で分けられる
          - key: APP_ENV
            value: production
            previewValue: preview

          - key: APP_NAME
            value: SocialFit
            previewValue: SocialFit (Preview)

          # Laravelは pgsql
          - key: DB_CONNECTION
            value: pgsql

          # Render Postgres の connectionString を注入
          - key: DATABASE_URL
            fromDatabase:
                name: socialfit-postgres-prod
                property: connectionString

          - fromGroup: secrets

databases:
    - name: socialfit-postgres-prod
      plan: starter
      previewPlan: free
